# Generated by Django 2.2.5 on 2019-09-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insert_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_ins',
            name='image',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
    ]
